name: Deploy DBT Models to BigQuery

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated version

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated version
      with:
        python-version: '3.8'

    - name: Install DBT
      run: |
        pip install --upgrade pip
        pip install dbt-bigquery

    - name: Create service account key file
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > ${{ runner.temp }}/gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/gcp-key.json" >> $GITHUB_ENV

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # Updated version
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2  # Updated version
      with:
        project_id: chicagotaxitrips-431912

    - name: Decode and Save GCP Key
      run: |
         echo "$GCP_SA_KEY_BASE64" | base64 -d > /tmp/gcp-key.json
         cat /tmp/gcp-key.json  # Display the decoded key (For debugging purposes only, remove this line after confirming it's correct)
      env:
        GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}
    
    - name: Set up dbt profiles directory
      run: |
        mkdir -p /home/runner/.dbt
        echo "$DBT_PROFILES_YML" > /home/runner/.dbt/profiles.yml
      env:
        DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}
         
    - name: Run DBT Models
      working-directory: ../chicago_taxi_project/dbt_taxi_project
      run: |
        dbt deps
        dbt seed
        dbt run
        dbt test

    - name: Check contents of target directory
      run: ls -la target/

    - name: Upload Artifacts (Optional)
      if: success()
      uses: actions/upload-artifact@v3  # Updated version
      with:
        name: dbt-logs
        path: target/*.log
