name: Deploy DBT Models to BigQuery

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure you're using a compatible Python version

    - name: Install DBT
      run: |
        pip install --upgrade pip
        pip install dbt-bigquery

    - name: Create service account key file
      run: echo "${{ secrets.GCP_SA_KEY }}" > ${{ runner.temp }}/gcp-key.json

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: chicagotaxitrips-431912
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json

    - name: Set up DBT Profiles
      run: |
        mkdir -p ~/.dbt
        echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
      env:
        DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}  # Ensure this secret is properly set

    - name: Run DBT Models
      working-directory: ../chicago_taxi_project/dbt_taxi_project  # Adjust if needed
      run: |
        dbt deps    # Install dependencies
        dbt seed    # Load seeds (optional)
        dbt run     # Run the models
        dbt test    # Run tests (optional)
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json

    - name: Upload Artifacts (Optional)
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: dbt-logs
        path: target/*.log
