name: Deploy DBT Models to BigQuery

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure you're using a compatible Python version

    - name: Install DBT
      run: |
        pip install --upgrade pip
        pip install dbt-bigquery

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: chicagotaxitrips-431912

    - name: Set up DBT Profiles
      run: |
        mkdir -p ~/.dbt
        echo "$DBT_PROFILES" > ~/.dbt/profiles.yml
      env:
        DBT_PROFILES: ${{ secrets.DBT_PROFILES_YML }}  # Use secrets to store profiles.yml content

    - name: Run DBT Models
      run: |
        dbt deps    # Install dependencies
        dbt seed    # Load seeds (optional)
        dbt run     # Run the models
        dbt test    # Run tests (optional)

    - name: Upload Artifacts (Optional)
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: dbt-logs
        path: target/*.log
