name: Deploy DBT Models to BigQuery

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install DBT
      run: |
        pip install --upgrade pip
        pip install dbt-bigquery


    - name: Decode and Create Service Account Key File
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ${{ runner.temp }}/gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/gcp-key.json" >> $GITHUB_ENV

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: chicagotaxitrips-431912

    - name: Set up DBT Profiles
      run: |
        mkdir -p ~/.dbt
        echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
      env:
        DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}
    
    - name: Print GCP Key File (for debugging)
      run: cat ${{ runner.temp }}/gcp-key.json

    - name: Validate JSON Key
      run: jq . ${{ runner.temp }}/gcp-key.json
      
    - name: Run DBT Models
      working-directory: ../chicago_taxi_project/dbt_taxi_project
      run: |
        dbt deps
        dbt seed
        dbt run
        dbt test

    - name: Upload Artifacts (Optional)
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: dbt-logs
        path: target/*.log
